"use strict";

module.exports = {
  "amex": "American Express",
  "artificiallabs": "Artificial Labs",
  "baml": "Bank of America Merrill Lynch",
  "blackrock": "BlackRock",
  "bloomberg": "Bloomberg",
  "citadel": "Citadel Securities",
  "ef": "EF",
  "facebook": "Facebook",
  "g_research": "G-Research",
  "go_cardless": "Go Cardless",
  "gousto": "Gousto",
  "jane_street": "Jane Street",
  "jpmorgan": "J.P. Morgan",
  "jump_trading": "Jump Trading LLC",
  "liquidnet": "Liquidnet",
  "lseg": "London Stock Exchange Group",
  "macquarie": "Macquarie",
  "microsoft": "Microsoft",
  "netcraft": "Netcraft",
  "next_jump": "Next Jump",
  "oliver_wyman": "Oliver Wyman",
  "palantir": "Palantir",
  "pdtpartners": "PDT Partners",
  "samsungrd": "Samsung R&D",
  "schlumberger": "Schlumberger",
  "stakezero": "Stake Zero Ventures",
  "starleaf": "StarLeaf",
  "twosigma": "Two Sigma",
  "wluper": "Wluper"
}
